/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hasGit(): boolean
export declare function isGitRepository(path: string): boolean
export declare function getBranches(path: string): Array<string>
